/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMA = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int ENTERO = 7;
  /** RegularExpression Id. */
  int CADENA = 8;
  /** RegularExpression Id. */
  int DECIMAL = 9;
  /** RegularExpression Id. */
  int IMPRIMIR = 10;
  /** RegularExpression Id. */
  int CAPTURAR = 11;
  /** RegularExpression Id. */
  int SI = 12;
  /** RegularExpression Id. */
  int SINO = 13;
  /** RegularExpression Id. */
  int SELECCIONA = 14;
  /** RegularExpression Id. */
  int CASO = 15;
  /** RegularExpression Id. */
  int ROMPER = 16;
  /** RegularExpression Id. */
  int DEFECTO = 17;
  /** RegularExpression Id. */
  int PARA = 18;
  /** RegularExpression Id. */
  int MIENTRAS = 19;
  /** RegularExpression Id. */
  int HACER = 20;
  /** RegularExpression Id. */
  int SUMA = 21;
  /** RegularExpression Id. */
  int RESTA = 22;
  /** RegularExpression Id. */
  int MULTIPLICACION = 23;
  /** RegularExpression Id. */
  int DIVICION = 24;
  /** RegularExpression Id. */
  int RESIDUO = 25;
  /** RegularExpression Id. */
  int POT = 26;
  /** RegularExpression Id. */
  int IGUAL = 27;
  /** RegularExpression Id. */
  int MAYOR = 28;
  /** RegularExpression Id. */
  int MENOR = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int AP = 33;
  /** RegularExpression Id. */
  int CP = 34;
  /** RegularExpression Id. */
  int ALL = 35;
  /** RegularExpression Id. */
  int CLL = 36;
  /** RegularExpression Id. */
  int PC = 37;
  /** RegularExpression Id. */
  int PP = 38;
  /** RegularExpression Id. */
  int digitos = 39;
  /** RegularExpression Id. */
  int letras = 40;
  /** RegularExpression Id. */
  int ID = 41;
  /** RegularExpression Id. */
  int VALOR_ENTERO = 42;
  /** RegularExpression Id. */
  int VALOR_DECIMAL = 43;
  /** RegularExpression Id. */
  int VALOR_CADENA = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"programa\"",
    "\"fin\"",
    "\"entero\"",
    "\"cadena\"",
    "\"decimal\"",
    "\"imprimir\"",
    "\"capturar\"",
    "\"si\"",
    "\"sino\"",
    "\"seleciona\"",
    "\"caso\"",
    "\"romper\"",
    "\"defecto\"",
    "\"para\"",
    "\"mientras\"",
    "\"hacer\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "<digitos>",
    "<letras>",
    "<ID>",
    "<VALOR_ENTERO>",
    "<VALOR_DECIMAL>",
    "<VALOR_CADENA>",
  };

}
